FROM ruby:2.7-alpine

COPY . /

RUN apk add --update --no-cache \
        build-base \
        curl \
        git \
    && gem install \
        bundler:2.4.22 \
        rubocop \
    && bundle install
